from LLMs.llm_factory import LLMFactory
from schema.types import ValidationInput

class ValidationAgent:

    def __init__(self):
        self.llm = LLMFactory.get_llm(task_type='complex')
    
    def run(self, inp: ValidationInput):
        prompt = f"""
        You are a Validation Agent responsible for reviewing responses generated by {inp.source_agent} agent.
        Your job is to validate the response on three criteria:

        Factual Accuracy
        Ensure the response does not contain false, fabricated, or unsupported claims.

        Reasoning Soundness
        If reasoning is present, verify that the logic is consistent and conclusions follow from the explanation.

        Risk Compliance
        The response must not provide sure-shot, guaranteed, or deterministic answers, especially for personalized queries classified as medium or high risk.
        Such responses should remain general, educational, and cautious.

        User query:
        {inp.query}

        Intent: {inp.intent}
        Risk: {inp.risk}
        Personalized: {inp.personalized}

        Candidate response:
        {inp.candidate_response}

        Return JSON only (no markdown, no backticks, no extra text):
        {{
        "decision": "pass" or "fail",
        "reason": "short explanation"
        }}
        """
        return self.llm.invoke(prompt).content
        # raw_result = self.llm.invoke(prompt).content
        # result = json.loads(raw_result)

